### ISSUE TITLE
VimTex Inverse Search

### ISSUE THREAD

**Issue by xarthurx** [Neelfrost/dotfiles#1]
Hi, I found your repo by googling and was trying to use your VimTex settings.

After setting the SumatraPDF Inverse Search, when using it, I got:

```
Error detected while processing command line:
E492: Not an editor command: PackerLoad vimtex
E492: Not an editor command: VimtexInverseSearch 93 'PATH_TO_TEX_FILE\test.tex'
```
Are you using the settings under Windows?

**Comment by Neelfrost** [comment]
It works correctly on my end. 

Are you using packer.nvim? The errors seem to suggest packer.nvim and vimtex is not loaded or is not present.

`cmd /c start /min nvim --headless -c "PackerLoad vimtex" -c "VimtexInverseSearch %l '%f'"`

`-c "PackerLoad vimtex"` is only necessary if you are lazy loading vimtex using packer. If not, `cmd /c start /min nvim --headless -c "VimtexInverseSearch %l '%f'"` should work.

**Comment by xarthurx** [comment]
I'm using `Packer` through the distribution [NvChad](nvchad.github.io/).
I can do `:PackerLoad vimtex` in neovim.
But if I run `cmd /c start /min nvim --headless -c "PackerLoad vimtex"` in the cmd, it will give me the above error.

**Comment by Neelfrost** [comment]
I think NvChad lazy loads packer as well, hence the error.

**Comment by xarthurx** [comment]
Yeah, I mean, even doing `cmd /c start /min nvim --headless -c "PackerLoad vimtex"` is wrong... It should work even if `Packer` is lazy loaded?

**Comment by Neelfrost** [comment]
No it won't work, packer,nvim will be loaded on `VimEnter` event, which does not happen with `--headless` iirc. 
You can try removing [this line](https://github.com/NvChad/NvChad/blob/0cf5d77f72593593c6190373520d7826051b1a72/lua/plugins/init.lua#L18) in your config, to always load packer. It should work then.

**Comment by xarthurx** [comment]
> I think NvChad lazy loads packer as well, hence the error.

I misunderstood this. Now I see, since `Packer` is also lazy loaded, the command will not work...
I'll try your suggestions. Thank you!

**Comment by xarthurx** [comment]
https://github.com/NvChad/NvChad/issues/841

Add an issue here. If commenting that line, it will be revoked everytime the `NvChad` is updated.

**Comment by Neelfrost** [comment]
```
cmd /c start /min nvim --headless -c "packadd packer.nvim" -c "PackerLoad vimtex" -c "VimtexInverseSearch %l '%f'"
``` 
Does this work by any chance?

**Comment by xarthurx** [comment]
Nope.
even `cmd /c start /min nvim --headless -c "packadd packer.nvim" -c "PackerLoad vimtex"` is not working.

**Comment by Neelfrost** [comment]
Solution in https://github.com/NvChad/NvChad/issues/841, closing.
