### ISSUE TITLE
OmniSharp is not getting attached to the buffer

### ISSUE THREAD

**Issue by XeRA0** [Neelfrost/dotfiles#3]
Hello Neelfrost,

Firstly THANK YOU for this awesome well made nvim config i really like it.
-------
I am having an issue with using the config though for Unity Development Omnisharp is not getting attached to the buffer at all i tried a couple of things in the servers lua but to no avail any idea how can i fix that ? i have attached a screenshot   
![neovide_uSZzqNJFHX](https://user-images.githubusercontent.com/46050640/186527449-2527b2f8-f3a7-40f0-b936-76456b0bd6d5.png)

there is sln and the .csproj files that got generated by unity 
Thank you!

**Comment by Neelfrost** [comment]
> Firstly THANK YOU for this awesome well made nvim config i really like it.

Glad you liked it :)

> I am having an issue with using the config though for Unity Development Omnisharp is not getting attached to the buffer at all i tried a couple of things in the servers lua but to no avail any idea how can i fix that ? i have attached a screenshot

I'll look into it. Omnisharp never worked automatically for me; it took a lot of tweaking to get it to attach to the buffer.

**Comment by XeRA0** [comment]
Thank you!

**Comment by Neelfrost** [comment]
Please check if the lastest commit fixes it on your end!
Make sure to read the updated installation instructions!.

**Comment by XeRA0** [comment]
Hey Neelfrost 

Thank you for fixing it it's working great !
